### ISSUE TITLE
comments from MoveApps

### ISSUE THREAD

**Issue by andreakoelzsch** [arky/humaninfra-wildlife-interactions#1]
Hi Arky,
Thanks for your contribution to the coding challenge! There are a few things that you have to adapt with your code before I am able to build this into a functioning App. Please would you adapt those and then submit a new version? You timely submission to the challenge is OK, but please try to update until the end of the week.
1) In the appspec.json you have to set "createsArtifacts": true, else all your artefact files are not shown to the user
2) In the appspec.json please just delete the two parts about funding and references, if there are none that you want to enter (you could enter reference to MovingPandas if you wanted to).
3) in the app.py, please return the input data set at the end, so that the App can be integrated in a workflow where more than one thing is done with the data. Of course, you can also decide to pass on a modified set of locations. Dont forget to note what you pass on in the output specificaiton of the documentation readme.md
4) in the app.py you have to make sure that the app path is properly configured for MoveApps. Please use our inbuild function for it, like in this example: self.moveapps_io.create_artifacts_file('speed_map.png')
I think then, it should be ready for first build in MoveApps and you can test it there.
Best,
Andrea

**Comment by andreakoelzsch** [comment]
I have created two PRs for the remaining things. Hope that it helps

**Comment by arky** [comment]
Thank you, you are awesome @andreakoelzsch
